apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /longhorn
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
    # the host entry is only required if you want to control from what
    # URL this ingress is exposed. In my case I use host to distiguish
    # if the URL is access internally or externally. e.g.
    # if access using an internal host name, security is relaxed
    # if access from an external host name, require authentication
    host: pie4.lan
