apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /longhorn
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80

