apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: datadog
  namespace: infra
spec:
  repo: https://helm.datadoghq.com
  chart: datadog
  version: 3.6.5
  targetNamespace: datadog
  valuesContent: |-
    # Configure the node-based Agent
    datadog:
      # apiKey: <API Key>
      # "Set up the Istio integration"
      clusterChecks:
        enabled: true
      # Receiving traces
      apm:
        enabled: true
      # Set up Istio log collection
      logs:
        containerCollectAll: true
        enabled: true
      acExclude: "name:datadog-agent name:datadog-cluster-agent"
      # Enable the Process Agent and system probe
      processAgent:
        processCollection: true
      networkMonitoring:
        enabled: true

    # Configure the Cluster Agent
    clusterAgent:
      enabled: true
      # Disable automatic sidecar injection for Datadog Agent pods
      podAnnotations:
        sidecar.istio.io/inject: "false"

    # Disable automatic sidecar injection for Datadog Agent pods
    agents:
      podAnnotations:
        sidecar.istio.io/inject: "false"