apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kong-oss
spec:
  repo: https://charts.konghq.com
  chart: kong
  version: 2.14.0
  targetNamespace: kong
  valuesContent: |-
    image:
      repository: kong
      tag: "3.1"
