---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    istio-injection: disabled

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-subdir-external-provisioner
  namespace: infra
spec:
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  chart: nfs-subdir-external-provisioner
  version: 4.0.17
  targetNamespace: infra
  valuesContent: |-
    nfs:
      server: 192.168.1.5
      path: /volume1/k8s

