apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: vino-postgres
spec:
   replicas: 2
   image: postgres:14.6
   database:
      size: 5Gi
      storageClassName: longhorn-local

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: REPLICATION_PASSWORD               
