---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: guru.lin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # use staging server for experimentation and troubleshooting
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cnameStrategy: Follow
        route53:
          region: us-west-2
          accessKeyID: AKIAQL5RISWD24PJD5AL
          hostedZoneID: Z00868421PWBTNO5RU29G
          secretAccessKeySecretRef:
            name: my-aws-credential
            key: aws_secret_access_key
      selector:
        dnsZones:
        - "app.vino9.net"
